source("./R/clm__transformCallToFrame____main.R", local = environment())
source("./R/clm__getModelComponentsFromModelFrame____main.R", local = environment())
source("./R/clm__checkRequirements____main.R", local = environment())
source("./R/clm__getSigmaMatrix____main.R", local = environment())
source("./R/clm__setLongModelComponentsToWide____main.R", local = environment())
source("./R/clm__setWideModelComponentsToList____main.R", local = environment())
source("./R/clm__fitModel____main.R", local = environment())
source("./R/clm__organizeResults____main.R", local = environment())
