source("./R/clm__checkRequirements__checkResponseRequirements.R", local = environment())
source("./R/clm__checkRequirements__checkExplanatoryRequirements.R", local = environment())
source("./R/clm__checkRequirements__checkWavesRequirements.R", local = environment())
source("./R/clm__checkRequirements__checkIdsRequirements.R", local = environment())
source("./R/clm__checkRequirements__checkWeightsRequirements.R", local = environment())
source("./R/clm__checkRequirements__checkStratumRequirements.R", local = environment())
source("./R/clm__checkRequirements__checkClusterRequirements.R", local = environment())
source("./R/clm__checkRequirements__checkSigmaRequirements.R", local = environment())
