source("./R/cov_clm__summary.clm.theta__getThetaTable.R", local = environment())
source("./R/cov_clm__summary.clm.theta__getOptimTable.R", local = environment())
source("./R/cov_clm__summary.clm.theta__catCall.R", local = environment())
source("./R/cov_clm__summary.clm.theta__catFitTypes.R", local = environment())
source("./R/cov_clm__summary.clm.theta__catFitResults.R", local = environment())
source("./R/cov_clm__summary.clm.theta__catOptimDetails.R", local = environment())
source("./R/cov_clm__summary.clm.theta__catSigmaThetaMatrix.R", local = environment())
source("./R/cov_clm__summary.clm.theta__catGoodnessOfFitMeasures.R", local = environment())
